public enum Animal {
    LION, TIGER, BEAR, MONKEY, ZEBRA, OSTRICH, SNAKE, SPIDER, ALLIGATOR,
        CROCODILE, YELLOW_JACKET, TURTLE, FROG, OWL, FOX, ELEPHANT, RHINO,
        THE_THOMAS_IS_BAD_AT_COMING_UP_WITH_ANIMAL_NAMES_SO_HE_MADE_ONE_UP;
}
